# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SERT_GUI_CONDIG.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 634)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setTitle("")
        self.groupBox.setFlat(True)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Controlo = QtWidgets.QTabWidget(self.groupBox)
        self.Controlo.setEnabled(True)
        self.Controlo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Controlo.setTabPosition(QtWidgets.QTabWidget.West)
        self.Controlo.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.Controlo.setObjectName("Controlo")
        self.Transistors = QtWidgets.QWidget()
        self.Transistors.setObjectName("Transistors")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Transistors)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_10 = QtWidgets.QGroupBox(self.Transistors)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.t1CriarModeloButton = QtWidgets.QPushButton(self.groupBox_10)
        self.t1CriarModeloButton.setObjectName("t1CriarModeloButton")
        self.gridLayout_10.addWidget(self.t1CriarModeloButton, 1, 0, 1, 1)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_10)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.t1SBox = QtWidgets.QSpinBox(self.groupBox_10)
        self.t1SBox.setMaximum(255)
        self.t1SBox.setObjectName("t1SBox")
        self.horizontalLayout_3.addWidget(self.t1SBox)
        self.formLayout_9.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.t1EnviarButton = QtWidgets.QPushButton(self.groupBox_10)
        self.t1EnviarButton.setObjectName("t1EnviarButton")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t1EnviarButton)
        self.gridLayout_10.addLayout(self.formLayout_9, 0, 0, 1, 1)
        self.t1ModelTBrowser = QtWidgets.QTextBrowser(self.groupBox_10)
        self.t1ModelTBrowser.setObjectName("t1ModelTBrowser")
        self.gridLayout_10.addWidget(self.t1ModelTBrowser, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_10)
        self.groupBox_11 = QtWidgets.QGroupBox(self.Transistors)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.t2CriarModeloButton = QtWidgets.QPushButton(self.groupBox_11)
        self.t2CriarModeloButton.setObjectName("t2CriarModeloButton")
        self.gridLayout_11.addWidget(self.t2CriarModeloButton, 1, 0, 1, 1)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.groupBox_11)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.t2SBox = QtWidgets.QSpinBox(self.groupBox_11)
        self.t2SBox.setMaximum(255)
        self.t2SBox.setObjectName("t2SBox")
        self.horizontalLayout_4.addWidget(self.t2SBox)
        self.formLayout_10.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        self.t2EnviarButton = QtWidgets.QPushButton(self.groupBox_11)
        self.t2EnviarButton.setObjectName("t2EnviarButton")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t2EnviarButton)
        self.gridLayout_11.addLayout(self.formLayout_10, 0, 0, 1, 1)
        self.t2ModelTBrowser = QtWidgets.QTextBrowser(self.groupBox_11)
        self.t2ModelTBrowser.setObjectName("t2ModelTBrowser")
        self.gridLayout_11.addWidget(self.t2ModelTBrowser, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_11)
        self.Controlo.addTab(self.Transistors, "")
        self.LEDs = QtWidgets.QWidget()
        self.LEDs.setObjectName("LEDs")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.LEDs)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_8 = QtWidgets.QGroupBox(self.LEDs)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.groupBox_8)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.l1SBox = QtWidgets.QSpinBox(self.groupBox_8)
        self.l1SBox.setMaximum(255)
        self.l1SBox.setObjectName("l1SBox")
        self.horizontalLayout_5.addWidget(self.l1SBox)
        self.formLayout_7.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_5)
        self.l1EnviarButton = QtWidgets.QPushButton(self.groupBox_8)
        self.l1EnviarButton.setObjectName("l1EnviarButton")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.l1EnviarButton)
        self.gridLayout_8.addLayout(self.formLayout_7, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.LEDs)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.groupBox_9)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.l2SBox = QtWidgets.QSpinBox(self.groupBox_9)
        self.l2SBox.setMaximum(255)
        self.l2SBox.setObjectName("l2SBox")
        self.horizontalLayout_6.addWidget(self.l2SBox)
        self.formLayout_8.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_6)
        self.l2EnviarButton = QtWidgets.QPushButton(self.groupBox_9)
        self.l2EnviarButton.setObjectName("l2EnviarButton")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.l2EnviarButton)
        self.gridLayout_9.addLayout(self.formLayout_8, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBox_9)
        self.Controlo.addTab(self.LEDs, "")
        self.OnOff = QtWidgets.QWidget()
        self.OnOff.setObjectName("OnOff")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.OnOff)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_6 = QtWidgets.QGroupBox(self.OnOff)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox_6)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ooT1TargetDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.ooT1TargetDSBox.setDecimals(1)
        self.ooT1TargetDSBox.setSingleStep(0.323)
        self.ooT1TargetDSBox.setProperty("value", 50.1)
        self.ooT1TargetDSBox.setObjectName("ooT1TargetDSBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ooT1TargetDSBox)
        self.ooT1StartButton = QtWidgets.QPushButton(self.groupBox_6)
        self.ooT1StartButton.setObjectName("ooT1StartButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ooT1StartButton)
        self.gridLayout_3.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.OnOff)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_24 = QtWidgets.QLabel(self.groupBox_7)
        self.label_24.setObjectName("label_24")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.ooT2TargetDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_7)
        self.ooT2TargetDSBox.setDecimals(1)
        self.ooT2TargetDSBox.setSingleStep(0.323)
        self.ooT2TargetDSBox.setProperty("value", 50.1)
        self.ooT2TargetDSBox.setObjectName("ooT2TargetDSBox")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ooT2TargetDSBox)
        self.ooT2StartButton = QtWidgets.QPushButton(self.groupBox_7)
        self.ooT2StartButton.setObjectName("ooT2StartButton")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ooT2StartButton)
        self.gridLayout_7.addLayout(self.formLayout_6, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.groupBox_7)
        self.Controlo.addTab(self.OnOff, "")
        self.Histerese = QtWidgets.QWidget()
        self.Histerese.setObjectName("Histerese")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Histerese)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_4 = QtWidgets.QGroupBox(self.Histerese)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.hstT1TargetDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.hstT1TargetDSBox.setDecimals(1)
        self.hstT1TargetDSBox.setMinimum(20.0)
        self.hstT1TargetDSBox.setSingleStep(0.323)
        self.hstT1TargetDSBox.setProperty("value", 50.1)
        self.hstT1TargetDSBox.setObjectName("hstT1TargetDSBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hstT1TargetDSBox)
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.hstT1ErroDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.hstT1ErroDSBox.setDecimals(1)
        self.hstT1ErroDSBox.setProperty("value", 1.0)
        self.hstT1ErroDSBox.setObjectName("hstT1ErroDSBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hstT1ErroDSBox)
        self.hstT1StartButton = QtWidgets.QPushButton(self.groupBox_4)
        self.hstT1StartButton.setObjectName("hstT1StartButton")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.hstT1StartButton)
        self.gridLayout_4.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.Histerese)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.hstT2TargetDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.hstT2TargetDSBox.setDecimals(1)
        self.hstT2TargetDSBox.setMinimum(20.0)
        self.hstT2TargetDSBox.setSingleStep(0.323)
        self.hstT2TargetDSBox.setProperty("value", 50.1)
        self.hstT2TargetDSBox.setObjectName("hstT2TargetDSBox")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hstT2TargetDSBox)
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.hstT2ErroDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.hstT2ErroDSBox.setDecimals(1)
        self.hstT2ErroDSBox.setProperty("value", 1.0)
        self.hstT2ErroDSBox.setObjectName("hstT2ErroDSBox")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.hstT2ErroDSBox)
        self.hstT2StartButton = QtWidgets.QPushButton(self.groupBox_5)
        self.hstT2StartButton.setObjectName("hstT2StartButton")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.hstT2StartButton)
        self.gridLayout_6.addLayout(self.formLayout_5, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_5)
        self.Controlo.addTab(self.Histerese, "")
        self.PID = QtWidgets.QWidget()
        self.PID.setObjectName("PID")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.PID)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.PID)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.pidT1TargetDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.pidT1TargetDSBox.setDecimals(1)
        self.pidT1TargetDSBox.setMinimum(20.0)
        self.pidT1TargetDSBox.setSingleStep(0.323)
        self.pidT1TargetDSBox.setProperty("value", 50.1)
        self.pidT1TargetDSBox.setObjectName("pidT1TargetDSBox")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pidT1TargetDSBox)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.pidT1PDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.pidT1PDSBox.setWrapping(False)
        self.pidT1PDSBox.setFrame(True)
        self.pidT1PDSBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pidT1PDSBox.setProperty("showGroupSeparator", False)
        self.pidT1PDSBox.setDecimals(3)
        self.pidT1PDSBox.setMaximum(9999.0)
        self.pidT1PDSBox.setObjectName("pidT1PDSBox")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pidT1PDSBox)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.pidT1IDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.pidT1IDSBox.setWrapping(False)
        self.pidT1IDSBox.setFrame(True)
        self.pidT1IDSBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pidT1IDSBox.setProperty("showGroupSeparator", False)
        self.pidT1IDSBox.setDecimals(3)
        self.pidT1IDSBox.setMaximum(9999.0)
        self.pidT1IDSBox.setObjectName("pidT1IDSBox")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pidT1IDSBox)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.pidT1DDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.pidT1DDSBox.setWrapping(False)
        self.pidT1DDSBox.setFrame(True)
        self.pidT1DDSBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pidT1DDSBox.setProperty("showGroupSeparator", False)
        self.pidT1DDSBox.setDecimals(3)
        self.pidT1DDSBox.setMaximum(9999.0)
        self.pidT1DDSBox.setObjectName("pidT1DDSBox")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pidT1DDSBox)
        self.pidT1StartButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pidT1StartButton.setMinimumSize(QtCore.QSize(0, 20))
        self.pidT1StartButton.setObjectName("pidT1StartButton")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pidT1StartButton)
        self.pidT1AWcheckBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.pidT1AWcheckBox.setEnabled(False)
        self.pidT1AWcheckBox.setMinimumSize(QtCore.QSize(0, 20))
        self.pidT1AWcheckBox.setObjectName("pidT1AWcheckBox")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pidT1AWcheckBox)
        self.gridLayout_13.addLayout(self.formLayout_3, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.t1ModeloCBox = QtWidgets.QComboBox(self.groupBox_2)
        self.t1ModeloCBox.setObjectName("t1ModeloCBox")
        self.horizontalLayout_7.addWidget(self.t1ModeloCBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.t1ControloCBox = QtWidgets.QComboBox(self.groupBox_2)
        self.t1ControloCBox.setObjectName("t1ControloCBox")
        self.t1ControloCBox.addItem("")
        self.t1ControloCBox.addItem("")
        self.t1ControloCBox.addItem("")
        self.horizontalLayout_8.addWidget(self.t1ControloCBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_15.addWidget(self.label_28)
        self.t1MetodoCBox = QtWidgets.QComboBox(self.groupBox_2)
        self.t1MetodoCBox.setObjectName("t1MetodoCBox")
        self.t1MetodoCBox.addItem("")
        self.t1MetodoCBox.addItem("")
        self.t1MetodoCBox.addItem("")
        self.t1MetodoCBox.addItem("")
        self.horizontalLayout_15.addWidget(self.t1MetodoCBox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.t1CalibrateButton = QtWidgets.QPushButton(self.groupBox_2)
        self.t1CalibrateButton.setMinimumSize(QtCore.QSize(0, 20))
        self.t1CalibrateButton.setObjectName("t1CalibrateButton")
        self.verticalLayout_3.addWidget(self.t1CalibrateButton)
        self.gridLayout_13.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.PID)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.pidT2TargetDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pidT2TargetDSBox.setDecimals(1)
        self.pidT2TargetDSBox.setMinimum(20.0)
        self.pidT2TargetDSBox.setSingleStep(0.323)
        self.pidT2TargetDSBox.setProperty("value", 50.1)
        self.pidT2TargetDSBox.setObjectName("pidT2TargetDSBox")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pidT2TargetDSBox)
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.pidT2PDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pidT2PDSBox.setWrapping(False)
        self.pidT2PDSBox.setFrame(True)
        self.pidT2PDSBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pidT2PDSBox.setProperty("showGroupSeparator", False)
        self.pidT2PDSBox.setDecimals(3)
        self.pidT2PDSBox.setMaximum(9999.0)
        self.pidT2PDSBox.setObjectName("pidT2PDSBox")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pidT2PDSBox)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.pidT2IDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pidT2IDSBox.setWrapping(False)
        self.pidT2IDSBox.setFrame(True)
        self.pidT2IDSBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pidT2IDSBox.setProperty("showGroupSeparator", False)
        self.pidT2IDSBox.setDecimals(3)
        self.pidT2IDSBox.setMaximum(9999.0)
        self.pidT2IDSBox.setObjectName("pidT2IDSBox")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pidT2IDSBox)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.pidT2DDSBox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.pidT2DDSBox.setWrapping(False)
        self.pidT2DDSBox.setFrame(True)
        self.pidT2DDSBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.pidT2DDSBox.setProperty("showGroupSeparator", False)
        self.pidT2DDSBox.setDecimals(3)
        self.pidT2DDSBox.setMaximum(9999.0)
        self.pidT2DDSBox.setObjectName("pidT2DDSBox")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pidT2DDSBox)
        self.pidT2StartButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pidT2StartButton.setMinimumSize(QtCore.QSize(0, 20))
        self.pidT2StartButton.setObjectName("pidT2StartButton")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pidT2StartButton)
        self.pidT2AWcheckBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.pidT2AWcheckBox.setEnabled(False)
        self.pidT2AWcheckBox.setObjectName("pidT2AWcheckBox")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.pidT2AWcheckBox)
        self.gridLayout_14.addLayout(self.formLayout_4, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.t2ModeloCBox = QtWidgets.QComboBox(self.groupBox_3)
        self.t2ModeloCBox.setObjectName("t2ModeloCBox")
        self.horizontalLayout_9.addWidget(self.t2ModeloCBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_10.addWidget(self.label_12)
        self.t2ControloCBox = QtWidgets.QComboBox(self.groupBox_3)
        self.t2ControloCBox.setObjectName("t2ControloCBox")
        self.t2ControloCBox.addItem("")
        self.t2ControloCBox.addItem("")
        self.t2ControloCBox.addItem("")
        self.horizontalLayout_10.addWidget(self.t2ControloCBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_16.addWidget(self.label_29)
        self.t2MetodoCBox = QtWidgets.QComboBox(self.groupBox_3)
        self.t2MetodoCBox.setObjectName("t2MetodoCBox")
        self.t2MetodoCBox.addItem("")
        self.t2MetodoCBox.addItem("")
        self.t2MetodoCBox.addItem("")
        self.t2MetodoCBox.addItem("")
        self.horizontalLayout_16.addWidget(self.t2MetodoCBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_16)
        self.t2CalibrateButton = QtWidgets.QPushButton(self.groupBox_3)
        self.t2CalibrateButton.setMinimumSize(QtCore.QSize(0, 20))
        self.t2CalibrateButton.setObjectName("t2CalibrateButton")
        self.verticalLayout_4.addWidget(self.t2CalibrateButton)
        self.gridLayout_14.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.groupBox_3)
        self.Controlo.addTab(self.PID, "")
        self.Modelos = QtWidgets.QWidget()
        self.Modelos.setObjectName("Modelos")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.Modelos)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_27 = QtWidgets.QLabel(self.Modelos)
        self.label_27.setObjectName("label_27")
        self.gridLayout_12.addWidget(self.label_27, 0, 0, 1, 1)
        self.removeModelButton = QtWidgets.QPushButton(self.Modelos)
        self.removeModelButton.setEnabled(False)
        self.removeModelButton.setObjectName("removeModelButton")
        self.gridLayout_12.addWidget(self.removeModelButton, 2, 0, 1, 1)
        self.splitter_4 = QtWidgets.QSplitter(self.Modelos)
        self.splitter_4.setOrientation(QtCore.Qt.Vertical)
        self.splitter_4.setObjectName("splitter_4")
        self.modelListWidget = QtWidgets.QListWidget(self.splitter_4)
        self.modelListWidget.setObjectName("modelListWidget")
        self.modelosTextBrowser = QtWidgets.QTextBrowser(self.splitter_4)
        self.modelosTextBrowser.setObjectName("modelosTextBrowser")
        self.gridLayout_12.addWidget(self.splitter_4, 1, 0, 1, 1)
        self.Controlo.addTab(self.Modelos, "")
        self.gridLayout_2.addWidget(self.Controlo, 0, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(40, 20))
        self.label.setMaximumSize(QtCore.QSize(40, 25))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.portaCBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.portaCBox.sizePolicy().hasHeightForWidth())
        self.portaCBox.setSizePolicy(sizePolicy)
        self.portaCBox.setMinimumSize(QtCore.QSize(125, 20))
        self.portaCBox.setMaximumSize(QtCore.QSize(125, 25))
        self.portaCBox.setObjectName("portaCBox")
        self.horizontalLayout.addWidget(self.portaCBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.connectionLabel = QtWidgets.QLabel(self.layoutWidget)
        self.connectionLabel.setMinimumSize(QtCore.QSize(100, 20))
        self.connectionLabel.setMaximumSize(QtCore.QSize(100, 25))
        self.connectionLabel.setScaledContents(False)
        self.connectionLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.connectionLabel.setObjectName("connectionLabel")
        self.horizontalLayout_2.addWidget(self.connectionLabel)
        self.conectarButton = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conectarButton.sizePolicy().hasHeightForWidth())
        self.conectarButton.setSizePolicy(sizePolicy)
        self.conectarButton.setMinimumSize(QtCore.QSize(65, 20))
        self.conectarButton.setMaximumSize(QtCore.QSize(65, 25))
        self.conectarButton.setObjectName("conectarButton")
        self.horizontalLayout_2.addWidget(self.conectarButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.graphWindow = GraphicsLayoutWidget(self.splitter_2)
        self.graphWindow.setObjectName("graphWindow")
        self.frame = QtWidgets.QFrame(self.splitter_2)
        self.frame.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.temp1StartQButton = QtWidgets.QPushButton(self.frame)
        self.temp1StartQButton.setMaximumSize(QtCore.QSize(65, 16777215))
        self.temp1StartQButton.setObjectName("temp1StartQButton")
        self.horizontalLayout_11.addWidget(self.temp1StartQButton)
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_11.addWidget(self.label_25)
        self.temp1TAEdit = QtWidgets.QLineEdit(self.frame)
        self.temp1TAEdit.setEnabled(False)
        self.temp1TAEdit.setMaximumSize(QtCore.QSize(95, 16777215))
        self.temp1TAEdit.setInputMask("")
        self.temp1TAEdit.setText("")
        self.temp1TAEdit.setMaxLength(4)
        self.temp1TAEdit.setObjectName("temp1TAEdit")
        self.horizontalLayout_11.addWidget(self.temp1TAEdit)
        self.temp1TcheckBox = QtWidgets.QCheckBox(self.frame)
        self.temp1TcheckBox.setEnabled(False)
        self.temp1TcheckBox.setMaximumSize(QtCore.QSize(95, 16777215))
        self.temp1TcheckBox.setObjectName("temp1TcheckBox")
        self.horizontalLayout_11.addWidget(self.temp1TcheckBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.temp1PcheckBox = QtWidgets.QCheckBox(self.frame)
        self.temp1PcheckBox.setEnabled(False)
        self.temp1PcheckBox.setMaximumSize(QtCore.QSize(30, 16777215))
        self.temp1PcheckBox.setCheckable(True)
        self.temp1PcheckBox.setObjectName("temp1PcheckBox")
        self.horizontalLayout_13.addWidget(self.temp1PcheckBox)
        self.temp1IcheckBox = QtWidgets.QCheckBox(self.frame)
        self.temp1IcheckBox.setEnabled(False)
        self.temp1IcheckBox.setMaximumSize(QtCore.QSize(30, 16777215))
        self.temp1IcheckBox.setObjectName("temp1IcheckBox")
        self.horizontalLayout_13.addWidget(self.temp1IcheckBox)
        self.temp1DcheckBox = QtWidgets.QCheckBox(self.frame)
        self.temp1DcheckBox.setEnabled(False)
        self.temp1DcheckBox.setMaximumSize(QtCore.QSize(30, 16777215))
        self.temp1DcheckBox.setObjectName("temp1DcheckBox")
        self.horizontalLayout_13.addWidget(self.temp1DcheckBox)
        self.temp1UcheckBox = QtWidgets.QCheckBox(self.frame)
        self.temp1UcheckBox.setEnabled(False)
        self.temp1UcheckBox.setMaximumSize(QtCore.QSize(30, 16777215))
        self.temp1UcheckBox.setObjectName("temp1UcheckBox")
        self.horizontalLayout_13.addWidget(self.temp1UcheckBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.temp2StartQButton = QtWidgets.QPushButton(self.frame)
        self.temp2StartQButton.setMaximumSize(QtCore.QSize(65, 16777215))
        self.temp2StartQButton.setObjectName("temp2StartQButton")
        self.horizontalLayout_12.addWidget(self.temp2StartQButton)
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_12.addWidget(self.label_26)
        self.temp2TAEdit = QtWidgets.QLineEdit(self.frame)
        self.temp2TAEdit.setEnabled(False)
        self.temp2TAEdit.setMaximumSize(QtCore.QSize(95, 16777215))
        self.temp2TAEdit.setMaxLength(4)
        self.temp2TAEdit.setObjectName("temp2TAEdit")
        self.horizontalLayout_12.addWidget(self.temp2TAEdit)
        self.temp2TcheckBox = QtWidgets.QCheckBox(self.frame)
        self.temp2TcheckBox.setEnabled(False)
        self.temp2TcheckBox.setMaximumSize(QtCore.QSize(95, 16777215))
        self.temp2TcheckBox.setObjectName("temp2TcheckBox")
        self.horizontalLayout_12.addWidget(self.temp2TcheckBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.temp2PcheckBox = QtWidgets.QCheckBox(self.frame)
        self.temp2PcheckBox.setEnabled(False)
        self.temp2PcheckBox.setMaximumSize(QtCore.QSize(30, 16777215))
        self.temp2PcheckBox.setObjectName("temp2PcheckBox")
        self.horizontalLayout_14.addWidget(self.temp2PcheckBox)
        self.temp2IcheckBox = QtWidgets.QCheckBox(self.frame)
        self.temp2IcheckBox.setEnabled(False)
        self.temp2IcheckBox.setMaximumSize(QtCore.QSize(30, 16777215))
        self.temp2IcheckBox.setObjectName("temp2IcheckBox")
        self.horizontalLayout_14.addWidget(self.temp2IcheckBox)
        self.temp2DcheckBox = QtWidgets.QCheckBox(self.frame)
        self.temp2DcheckBox.setEnabled(False)
        self.temp2DcheckBox.setMaximumSize(QtCore.QSize(30, 16777215))
        self.temp2DcheckBox.setObjectName("temp2DcheckBox")
        self.horizontalLayout_14.addWidget(self.temp2DcheckBox)
        self.temp2UcheckBox = QtWidgets.QCheckBox(self.frame)
        self.temp2UcheckBox.setEnabled(False)
        self.temp2UcheckBox.setMaximumSize(QtCore.QSize(30, 16777215))
        self.temp2UcheckBox.setObjectName("temp2UcheckBox")
        self.horizontalLayout_14.addWidget(self.temp2UcheckBox)
        self.verticalLayout_12.addLayout(self.horizontalLayout_14)
        self.gridLayout_5.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.ref3v3RButton = QtWidgets.QRadioButton(self.frame)
        self.ref3v3RButton.setEnabled(False)
        self.ref3v3RButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ref3v3RButton.setChecked(True)
        self.ref3v3RButton.setObjectName("ref3v3RButton")
        self.verticalLayout_9.addWidget(self.ref3v3RButton)
        self.ref5vButton = QtWidgets.QRadioButton(self.frame)
        self.ref5vButton.setEnabled(False)
        self.ref5vButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.ref5vButton.setObjectName("ref5vButton")
        self.verticalLayout_9.addWidget(self.ref5vButton)
        self.verticalLayout_14.addLayout(self.verticalLayout_9)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.graph1SaveButton = QtWidgets.QPushButton(self.frame)
        self.graph1SaveButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.graph1SaveButton.setObjectName("graph1SaveButton")
        self.verticalLayout_13.addWidget(self.graph1SaveButton)
        self.graph2SaveButton = QtWidgets.QPushButton(self.frame)
        self.graph2SaveButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.graph2SaveButton.setObjectName("graph2SaveButton")
        self.verticalLayout_13.addWidget(self.graph2SaveButton)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.gridLayout_5.addLayout(self.verticalLayout_14, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.splitter_3, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.Controlo.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Transístor 1"))
        self.t1CriarModeloButton.setText(_translate("MainWindow", "Criar Modelo"))
        self.label_8.setText(_translate("MainWindow", "Intensidade:"))
        self.t1EnviarButton.setText(_translate("MainWindow", "Enviar"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Transístor 2"))
        self.t2CriarModeloButton.setText(_translate("MainWindow", "Criar Modelo"))
        self.label_9.setText(_translate("MainWindow", "Intensidade:"))
        self.t2EnviarButton.setText(_translate("MainWindow", "Enviar"))
        self.Controlo.setTabText(self.Controlo.indexOf(self.Transistors), _translate("MainWindow", "Transístores"))
        self.groupBox_8.setTitle(_translate("MainWindow", "LED Verde"))
        self.label_11.setText(_translate("MainWindow", "Luminusidade:"))
        self.l1EnviarButton.setText(_translate("MainWindow", "Enviar"))
        self.groupBox_9.setTitle(_translate("MainWindow", "LED Vermelho"))
        self.label_13.setText(_translate("MainWindow", "Luminusidade:"))
        self.l2EnviarButton.setText(_translate("MainWindow", "Enviar"))
        self.Controlo.setTabText(self.Controlo.indexOf(self.LEDs), _translate("MainWindow", "LEDs"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Transístor 1"))
        self.label_3.setText(_translate("MainWindow", "Target (ºC):"))
        self.ooT1TargetDSBox.setSuffix(_translate("MainWindow", "ºC"))
        self.ooT1StartButton.setText(_translate("MainWindow", "Começar"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Transístor 2"))
        self.label_24.setText(_translate("MainWindow", "Target (ºC):"))
        self.ooT2TargetDSBox.setSuffix(_translate("MainWindow", "ºC"))
        self.ooT2StartButton.setText(_translate("MainWindow", "Começar"))
        self.Controlo.setTabText(self.Controlo.indexOf(self.OnOff), _translate("MainWindow", "On-Off"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Transístor 1"))
        self.label_4.setText(_translate("MainWindow", "Target (ºC):"))
        self.hstT1TargetDSBox.setSuffix(_translate("MainWindow", "ºC"))
        self.label_5.setText(_translate("MainWindow", "Erro (h):"))
        self.hstT1ErroDSBox.setSuffix(_translate("MainWindow", "ºC"))
        self.hstT1StartButton.setText(_translate("MainWindow", "Começar"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Transístor 2"))
        self.label_22.setText(_translate("MainWindow", "Target (ºC):"))
        self.hstT2TargetDSBox.setSuffix(_translate("MainWindow", "ºC"))
        self.label_23.setText(_translate("MainWindow", "Erro (h):"))
        self.hstT2ErroDSBox.setSuffix(_translate("MainWindow", "ºC"))
        self.hstT2StartButton.setText(_translate("MainWindow", "Começar"))
        self.Controlo.setTabText(self.Controlo.indexOf(self.Histerese), _translate("MainWindow", "Histerese"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Transístor 1"))
        self.label_14.setText(_translate("MainWindow", "Target (ºC):"))
        self.label_15.setText(_translate("MainWindow", "P:"))
        self.label_16.setText(_translate("MainWindow", "I:"))
        self.label_17.setText(_translate("MainWindow", "D:"))
        self.pidT1StartButton.setText(_translate("MainWindow", "Começar"))
        self.pidT1AWcheckBox.setText(_translate("MainWindow", "Anti-Windup"))
        self.label_6.setText(_translate("MainWindow", "Modelo:"))
        self.label_7.setText(_translate("MainWindow", "Controlo:"))
        self.t1ControloCBox.setItemText(0, _translate("MainWindow", "P"))
        self.t1ControloCBox.setItemText(1, _translate("MainWindow", "PI"))
        self.t1ControloCBox.setItemText(2, _translate("MainWindow", "PID"))
        self.label_28.setText(_translate("MainWindow", "Método:"))
        self.t1MetodoCBox.setItemText(0, _translate("MainWindow", "Ziegler-Nichols Malha Aberta"))
        self.t1MetodoCBox.setItemText(1, _translate("MainWindow", "Cohen-Coon"))
        self.t1MetodoCBox.setItemText(2, _translate("MainWindow", "ITAE - Entradas de Referência"))
        self.t1MetodoCBox.setItemText(3, _translate("MainWindow", "ITAE - Rejeição a Perturbações"))
        self.t1CalibrateButton.setText(_translate("MainWindow", "Calibrar"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Transístor 2"))
        self.label_18.setText(_translate("MainWindow", "Target (ºC):"))
        self.label_19.setText(_translate("MainWindow", "P:"))
        self.label_20.setText(_translate("MainWindow", "I:"))
        self.label_21.setText(_translate("MainWindow", "D:"))
        self.pidT2StartButton.setText(_translate("MainWindow", "Começar"))
        self.pidT2AWcheckBox.setText(_translate("MainWindow", "Anti-windup"))
        self.label_10.setText(_translate("MainWindow", "Modelo:"))
        self.label_12.setText(_translate("MainWindow", "Controlo:"))
        self.t2ControloCBox.setItemText(0, _translate("MainWindow", "P"))
        self.t2ControloCBox.setItemText(1, _translate("MainWindow", "PI"))
        self.t2ControloCBox.setItemText(2, _translate("MainWindow", "PID"))
        self.label_29.setText(_translate("MainWindow", "Método:"))
        self.t2MetodoCBox.setItemText(0, _translate("MainWindow", "Ziegler-Nichols Malha Aberta"))
        self.t2MetodoCBox.setItemText(1, _translate("MainWindow", "Cohen-Coon"))
        self.t2MetodoCBox.setItemText(2, _translate("MainWindow", "ITAE - Entradas de Referência"))
        self.t2MetodoCBox.setItemText(3, _translate("MainWindow", "ITAE - Rejeição a Perturbações"))
        self.t2CalibrateButton.setText(_translate("MainWindow", "Calibrar"))
        self.Controlo.setTabText(self.Controlo.indexOf(self.PID), _translate("MainWindow", "PID"))
        self.label_27.setText(_translate("MainWindow", "Transístor - Temperatura inicial - Input"))
        self.removeModelButton.setText(_translate("MainWindow", "Remover Modelo"))
        self.Controlo.setTabText(self.Controlo.indexOf(self.Modelos), _translate("MainWindow", "Modelos"))
        self.label.setText(_translate("MainWindow", "  Porta:"))
        self.connectionLabel.setText(_translate("MainWindow", "Conexão: Desligada"))
        self.conectarButton.setText(_translate("MainWindow", "Conectar"))
        self.temp1StartQButton.setText(_translate("MainWindow", "Começar"))
        self.label_25.setText(_translate("MainWindow", "Tempo de amostragem"))
        self.temp1TAEdit.setPlaceholderText(_translate("MainWindow", "(em milisegundos)"))
        self.temp1TcheckBox.setText(_translate("MainWindow", "Temperatura 1"))
        self.temp1PcheckBox.setText(_translate("MainWindow", "P"))
        self.temp1IcheckBox.setText(_translate("MainWindow", "I"))
        self.temp1DcheckBox.setText(_translate("MainWindow", "D"))
        self.temp1UcheckBox.setText(_translate("MainWindow", "u"))
        self.temp2StartQButton.setText(_translate("MainWindow", "Começar"))
        self.label_26.setText(_translate("MainWindow", "Tempo de amostragem"))
        self.temp2TAEdit.setPlaceholderText(_translate("MainWindow", "(em milisegundos)"))
        self.temp2TcheckBox.setText(_translate("MainWindow", "Temperatura 2"))
        self.temp2PcheckBox.setText(_translate("MainWindow", "P"))
        self.temp2IcheckBox.setText(_translate("MainWindow", "I"))
        self.temp2DcheckBox.setText(_translate("MainWindow", "D"))
        self.temp2UcheckBox.setText(_translate("MainWindow", "u"))
        self.label_2.setText(_translate("MainWindow", "Referência do ADC"))
        self.ref3v3RButton.setText(_translate("MainWindow", "3,3V"))
        self.ref5vButton.setText(_translate("MainWindow", "5V"))
        self.graph1SaveButton.setText(_translate("MainWindow", "Guardar Plot 1"))
        self.graph2SaveButton.setText(_translate("MainWindow", "Guardar Plot 2"))

from pyqtgraph import GraphicsLayoutWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

